version: "3.7"

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    expose:
      - 5000
    environment:
      - FLASK_APP=./services/web/project/__init__.py
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    volumes:
      - static_volume:/home/app/web/project/static
    depends_on:
      - db
  db:
    build:
      context: ./services/web/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres

  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    ports:
      - 8080:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
