repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://github.com/ryanrhee/shellcheck-py
    rev: v0.7.1.1
    hooks:
      - id: shellcheck
